In [3]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [65]:

from seed_connectivity import SeedConnectivity
from nilearn import image
fc = SeedConnectivity(bold_path='/Users/rohinpalsule/Desktop/GLM')
import numpy as np
confound_filename = '/Users/rohinpalsule/Desktop/GLM/sub-5159/sub-5159_ses-3_task-StudyGW_desc-confounds_timeseries_filtered.tsv'
import pandas as pd

Output will be saved to: /Users/rohinpalsule/Documents/GitHub/R01-Analysis-fMRI/FuncCon/results/plot_seed_to_voxel_correlation
Running seed for Hippocampus. Make sure coordinates are correct!

In [66]:
event_df = fc.make_events_df()

early_tr = np.array(event_df[event_df['trial_type']==1]['TR'])
early_min = int(early_tr.min() - 1)
early_max = int(early_tr.max())

early_confound = pd.read_csv(confound_filename,sep='\t').iloc[early_min:early_max]
early_func = image.index_img('/Users/rohinpalsule/Desktop/GLM/sub-5159/sub-5159_ses-3_task-StudyGW_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz', slice(early_min, early_max))

late_tr = np.array(event_df[event_df['trial_type']==4]['TR'])
late_min = int(late_tr.min() - 1)
late_max = int(late_tr.max())

late_confound = pd.read_csv(confound_filename,sep='\t').iloc[late_min:late_max]
late_func = image.index_img('/Users/rohinpalsule/Desktop/GLM/sub-5159/sub-5159_ses-3_task-StudyGW_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz', slice(late_min, late_max))

In [71]:
early_confound

,global_signal,global_signal_power2,csf,csf_power2,white_matter,white_matter_power2,csf_wm,tcompcor,trans_x,trans_x_power2,trans_y,trans_y_power2,trans_z,trans_z_power2,rot_x,rot_x_power2,rot_y,rot_y_power2,rot_z,rot_z_power2
6,9804.875603,96135585.60,8346.820188,69669407.24,6185.981305,38266364.71,6348.020253,8697.269171,0.023059,0.000532,0.055487,0.003079,0.107738,0.011607,-0.000506,2.560000e-07,0.000000e+00,0.000000e+00,-0.000171,2.940000e-08
7,9815.873717,96351376.83,8422.464824,70937913.71,6185.267207,38257530.43,6346.529094,8729.877676,0.016665,0.000278,0.010084,0.000102,0.114957,0.013215,-0.000496,2.460000e-07,9.860000e-05,9.710000e-09,-0.000519,2.690000e-07
8,9820.358067,96439432.57,8389.911340,70390612.29,6185.009513,38254342.67,6350.324136,8807.417217,0.015488,0.000240,0.017607,0.000310,0.102477,0.010502,-0.000198,3.900000e-08,8.780000e-05,7.700000e-09,-0.000515,2.650000e-07
9,9830.699840,96642659.35,8412.976097,70778166.80,6191.969587,38340487.37,6350.899464,8846.853825,0.016969,0.000288,0.042081,0.001771,0.102271,0.010459,-0.000461,2.120000e-07,-9.030000e-23,8.160000e-45,-0.000690,4.760000e-07
10,9817.525413,96383805.24,8399.580411,70552951.09,6178.457304,38173334.65,6338.496445,8967.539334,0.019073,0.000364,-0.012500,0.000156,0.103858,0.010786,-0.000176,3.110000e-08,2.121110e-04,4.500000e-08,-0.000724,5.240000e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,9824.183751,96514586.38,8338.579537,69531908.69,6178.071447,38168566.81,6334.254090,8878.516541,-0.020505,0.000420,0.089102,0.007939,0.116185,0.013499,0.000201,4.040000e-08,2.009280e-03,4.040000e-06,-0.002031,4.130000e-06
98,9828.210923,96593729.95,8392.236224,70429628.84,6179.319826,38183993.51,6342.479344,8945.876229,-0.016664,0.000278,0.017286,0.000299,0.122346,0.014969,0.000064,4.160000e-09,2.259020e-03,5.100000e-06,-0.001924,3.700000e-06
99,9828.018427,96589946.20,8365.095649,69974825.21,6172.433943,38098940.78,6336.874018,8944.212441,-0.021960,0.000482,0.088794,0.007884,0.111169,0.012359,0.000275,7.570000e-08,2.009020e-03,4.040000e-06,-0.001838,3.380000e-06
100,9815.622579,96346446.62,8406.061900,70661876.66,6167.961682,38043751.31,6333.040064,8939.859145,-0.021740,0.000473,0.040987,0.001680,0.125471,0.015743,0.000098,9.580000e-09,2.259020e-03,5.100000e-06,-0.002117,4.480000e-06
101,9807.648206,96189963.32,8312.817222,69102930.16,6175.220605,38133349.52,6330.562591,8825.931699,-0.023823,0.000568,0.096994,0.009408,0.116477,0.013567,0.000260,6.740000e-08,2.259020e-03,5.100000e-06,-0.002033,4.130000e-06

In [55]:
type(early_min)

numpy.float64

In [60]:
early_confound

,global_signal,global_signal_power2,csf,csf_power2,white_matter,white_matter_power2,csf_wm,tcompcor,trans_x,trans_x_power2,trans_y,trans_y_power2,trans_z,trans_z_power2,rot_x,rot_x_power2,rot_y,rot_y_power2,rot_z,rot_z_power2
6,9804.875603,96135585.60,8346.820188,69669407.24,6185.981305,38266364.71,6348.020253,8697.269171,0.023059,0.000532,0.055487,0.003079,0.107738,0.011607,-0.000506,2.560000e-07,0.000000e+00,0.000000e+00,-0.000171,2.940000e-08
7,9815.873717,96351376.83,8422.464824,70937913.71,6185.267207,38257530.43,6346.529094,8729.877676,0.016665,0.000278,0.010084,0.000102,0.114957,0.013215,-0.000496,2.460000e-07,9.860000e-05,9.710000e-09,-0.000519,2.690000e-07
8,9820.358067,96439432.57,8389.911340,70390612.29,6185.009513,38254342.67,6350.324136,8807.417217,0.015488,0.000240,0.017607,0.000310,0.102477,0.010502,-0.000198,3.900000e-08,8.780000e-05,7.700000e-09,-0.000515,2.650000e-07
9,9830.699840,96642659.35,8412.976097,70778166.80,6191.969587,38340487.37,6350.899464,8846.853825,0.016969,0.000288,0.042081,0.001771,0.102271,0.010459,-0.000461,2.120000e-07,-9.030000e-23,8.160000e-45,-0.000690,4.760000e-07
10,9817.525413,96383805.24,8399.580411,70552951.09,6178.457304,38173334.65,6338.496445,8967.539334,0.019073,0.000364,-0.012500,0.000156,0.103858,0.010786,-0.000176,3.110000e-08,2.121110e-04,4.500000e-08,-0.000724,5.240000e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,9824.183751,96514586.38,8338.579537,69531908.69,6178.071447,38168566.81,6334.254090,8878.516541,-0.020505,0.000420,0.089102,0.007939,0.116185,0.013499,0.000201,4.040000e-08,2.009280e-03,4.040000e-06,-0.002031,4.130000e-06
98,9828.210923,96593729.95,8392.236224,70429628.84,6179.319826,38183993.51,6342.479344,8945.876229,-0.016664,0.000278,0.017286,0.000299,0.122346,0.014969,0.000064,4.160000e-09,2.259020e-03,5.100000e-06,-0.001924,3.700000e-06
99,9828.018427,96589946.20,8365.095649,69974825.21,6172.433943,38098940.78,6336.874018,8944.212441,-0.021960,0.000482,0.088794,0.007884,0.111169,0.012359,0.000275,7.570000e-08,2.009020e-03,4.040000e-06,-0.001838,3.380000e-06
100,9815.622579,96346446.62,8406.061900,70661876.66,6167.961682,38043751.31,6333.040064,8939.859145,-0.021740,0.000473,0.040987,0.001680,0.125471,0.015743,0.000098,9.580000e-09,2.259020e-03,5.100000e-06,-0.002117,4.480000e-06
101,9807.648206,96189963.32,8312.817222,69102930.16,6175.220605,38133349.52,6330.562591,8825.931699,-0.023823,0.000568,0.096994,0.009408,0.116477,0.013567,0.000260,6.740000e-08,2.259020e-03,5.100000e-06,-0.002033,4.130000e-06